# Generated by Django 4.2 on 2023-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
