# Generated by Django 4.2 on 2023-04-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_basket_price_alter_basket_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
