# Generated by Django 4.2 on 2023-05-03 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Data zamówienia')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='Data nadania')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Data dostarczenia')),
                ('paid', models.BooleanField(verbose_name='Opłacono')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data płatności')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dostawa', to='mysite.payment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Płatność', to='mysite.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
