# Generated by Django 4.2 on 2023-05-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_orderdetail_delete_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
