# Generated by Django 4.2 on 2023-05-04 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena'),
            preserve_default=False,
        ),
    ]
