from django.urls import path
from .views import category, delivery, order_details, order, payment, product, user

urlpatterns = [
    path('', product.HomePageView.as_view(), name="home"),
    path('product/create/', product.CreateProductView.as_view(), name="create-product"),
    path('product/<int:pk>/delete/', product.DeleteProductView.as_view(), name="delete-product"),
    path('product/<int:pk>/update/', product.UpdateProductView.as_view(), name="update-product"),
    path('product/<int:pk>/', product.ProductView.as_view(), name="details-product"),
    path('slider/<str:name>/', product.slider_view, name="slider"),
    path('category/create/', category.CreateCategoryView.as_view(), name="create-category"),
    path('category/<int:pk>/delete/', category.DeleteCategoryView.as_view(), name="delete-category"),
    path('category/<int:pk>/update/', category.UpdateCategoryView.as_view(), name="update-category"),
    path('category/<int:pk>/', category.CategoryView.as_view(), name="details-category"),
    path('category/', category.CategoryPageView.as_view(), name="category"),
    path('user/create/', user.CreateUser.as_view(), name="create-user"),
    path('contact/', user.contact_view, name="contact"),
    path('order_detail/', order_details.OrderDetailPageView.as_view(), name="order_detail"),
    path('order_detail/<int:pk>/delete/', order_details.DeleteOrderDetailView.as_view(), name="delete-order_detail"),
    path('order_detail/delete-all/', order_details.delete_all_order_detail, name="delete-all-order_detail"),
    path('order_detail/<int:pk>/update/', order_details.UpdateOrderDetailView.as_view(), name="update-order_detail"),
    path('order_detail/buy/', order_details.buy_view, name="buy-order_detail"),
    path('delivery/create/', delivery.CreateDeliveryView.as_view(), name="create-delivery"),
    path('delivery/<int:pk>/delete/', delivery.DeleteDeliveryView.as_view(), name="delete-delivery"),
    path('delivery/<int:pk>/update/', delivery.UpdateDeliveryView.as_view(), name="update-delivery"),
    path('delivery/<int:pk>/', delivery.DeliveryView.as_view(), name="details-delivery"),
    path('delivery/', delivery.DeliveryPageView.as_view(), name="delivery"),
    path('payment/create/', payment.CreatePaymentView.as_view(), name="create-payment"),
    path('payment/<int:pk>/delete/', payment.DeletePaymentView.as_view(), name="delete-payment"),
    path('payment/<int:pk>/update/', payment.UpdatePaymentView.as_view(), name="update-payment"),
    path('payment/<int:pk>/', payment.PaymentView.as_view(), name="details-payment"),
    path('payment/', payment.PaymentPageView.as_view(), name="payment"),
    path('order/create/', order.CreateOrderView.as_view(), name="create-order"),
    path('order/', order.OrderPageView.as_view(), name="order"),
    path('order/content/<int:pk>/', order.OrderContentView.as_view(), name="content-order"),
]